import boto3

access_token = "eyJraWQiOiJxeVlGRkFjdFp6TDNZUTNWMEowUW1RcWdRWjhvNWZ6czV2RjUzb3hMSlwvYz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI3MWJlNjk1My1kYjBmLTRiNjQtODExNy01YzlhMjkzN2EwNjQiLCJkZXZpY2Vfa2V5IjoiYXAtc291dGhlYXN0LTJfZGZlY2VmZmUtZjI5MS00YTZiLTg5YzgtZTEyNzk1MDhiNjcxIiwiZXZlbnRfaWQiOiJlNjA3NTllYy1kZTgzLTQwYjctODYzNS0yZTJhMjYwM2IxODYiLCJ0b2tlbl91c2UiOiJhY2Nlc3MiLCJzY29wZSI6ImF3cy5jb2duaXRvLnNpZ25pbi51c2VyLmFkbWluIiwiYXV0aF90aW1lIjoxNjIyNzg1NDM1LCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuYXAtc291dGhlYXN0LTIuYW1hem9uYXdzLmNvbVwvYXAtc291dGhlYXN0LTJfYXhLQkFwVEw1IiwiZXhwIjoxNjIyNzg5MDM1LCJpYXQiOjE2MjI3ODU0MzUsImp0aSI6IjNlM2E5OTQ0LWMxZWQtNDkyZS1iYzJkLTM4NjFmNmJjYjYyNyIsImNsaWVudF9pZCI6IjdwMGN1dmJqb2YzbnV2cDNobzJoaDNzcnVuIiwidXNlcm5hbWUiOiJhc29hIn0.afmCg6yxkGDzKlU3mxUiKdSGXbFsP6WcrhlWdy5_TqwUqAPpB9rVging5RoJZwMR5j_JE3rSy7nYRkVBZFRnVE7SrVx8mqcW8FOMkFLBwAwdDAMH_Y4hquszeJHQCZHmO3aAow9O2nrgSaOAXCME5etPZdrWXoHQ2awCvAgce9owGxzM8uPSHNrkFSU5x135mTir4HPYLMX20pNKwHC_ODnSEXewg9cUsu-dqxLlKpPZ9GD7jQIRjGDppM2fPneZAlWLXD28GfBviqqh8Pi4tyvXXzvtPhLbNIXZ96dH0uIqNeS3J6vScjnqI4xa7gyXZNnUS-glqDfqdTwHUO6tiw"

client = boto3.client('cognito-idp', region_name='ap-southeast-2')

response = client.get_user(
  AccessToken = access_token
)

print(response)

attr_sub = None
for attr in response['UserAttributes']:
  if attr['Name'] == 'sub':
    attr_sub = attr['Value']
    break
  
print('UserSub', attr_sub)